version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:4.1.3
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      KAFKA_OPTS: -Djava.security.auth.login.config=/var/docker/config/kafka_server_jaas.conf
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: SASL_PLAINTEXT://kafka:9093,PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9093,PLAINTEXT://kafka:9092
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      ZOOKEEPER_SASL_ENABLED: 'FALSE'
    volumes:
      - ./.docker/:/var/docker
  kafka-create-topics:
    image: confluentinc/cp-kafka:4.1.3
    depends_on:
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "party:1:1,role:1:1,contract:1:1,party_process_queue:1:1,role_process_queue:1:1,contract_process_queue:1:1,published:1:1"
    command: ["bash", "/var/docker/scripts/wait-for-it.sh", "kafka:9092", "--", "bash",
              "/var/docker/scripts/create-kafka-topics.sh"]
    volumes:
      - ./.docker/:/var/docker
  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.1.3
    ports:
      - 8082:8082
    depends_on:
      - kafka
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    ports:
      - 8000:8000
    depends_on:
      - kafka-rest
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest:8082"
      PROXY: "true"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
